# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_pb2 as grpc__pb2


class TransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFileToServer = channel.unary_unary(
                '/transmission.Transmission/SendFileToServer',
                request_serializer=grpc__pb2.SendFile.SerializeToString,
                response_deserializer=grpc__pb2.Status.FromString,
                )
        self.TakeFileFromServer = channel.unary_unary(
                '/transmission.Transmission/TakeFileFromServer',
                request_serializer=grpc__pb2.Path.SerializeToString,
                response_deserializer=grpc__pb2.TakeFile.FromString,
                )
        self.DeleteFileOnServer = channel.unary_unary(
                '/transmission.Transmission/DeleteFileOnServer',
                request_serializer=grpc__pb2.Path.SerializeToString,
                response_deserializer=grpc__pb2.Status.FromString,
                )


class TransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFileToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeFileFromServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileOnServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFileToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFileToServer,
                    request_deserializer=grpc__pb2.SendFile.FromString,
                    response_serializer=grpc__pb2.Status.SerializeToString,
            ),
            'TakeFileFromServer': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeFileFromServer,
                    request_deserializer=grpc__pb2.Path.FromString,
                    response_serializer=grpc__pb2.TakeFile.SerializeToString,
            ),
            'DeleteFileOnServer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileOnServer,
                    request_deserializer=grpc__pb2.Path.FromString,
                    response_serializer=grpc__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transmission.Transmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFileToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transmission.Transmission/SendFileToServer',
            grpc__pb2.SendFile.SerializeToString,
            grpc__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TakeFileFromServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transmission.Transmission/TakeFileFromServer',
            grpc__pb2.Path.SerializeToString,
            grpc__pb2.TakeFile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFileOnServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transmission.Transmission/DeleteFileOnServer',
            grpc__pb2.Path.SerializeToString,
            grpc__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
