# Form implementation generated from reading ui file 'maketDisable.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

#Add
from PyQt6.QtCore import Qt, QModelIndex


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.outImage.setGeometry(QtCore.QRect(427, 30, 341, 501))
        self.outImage.setText("")
        self.outImage.setObjectName("outImage")
        self.listFiles = QtWidgets.QListView(parent=self.centralwidget)
        self.listFiles.setEnabled(True)
        self.listFiles.setGeometry(QtCore.QRect(10, 30, 401, 501))
        self.listFiles.setStyleSheet("QListView{background-color: white; color: black}")
        self.listFiles.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listFiles.setDragEnabled(False)
        self.listFiles.setObjectName("listFiles")
        self.downButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(100, 529, 201, 21))
        self.downButton.setObjectName("downButton")
        self.upButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(100, 10, 201, 21))
        self.upButton.setObjectName("upButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # #Add
        # self.listFiles.clicked.connect(self.tesst)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.downButton.setText(_translate("MainWindow", "Down"))
        self.upButton.setText(_translate("MainWindow", "Up"))


    # ##Add
    # def tesst(self, l: QModelIndex):
    #     #ad.model()
    #     # print('\n-----------\n')
    #     # print(self.widget.currentIndex())
    #     #print(l.data(Qt.ItemDataRole.DecorationRole).pixmap(100, 100) , 'asfdfasd')
    #     self.outImage.setPixmap(l.data(Qt.ItemDataRole.DecorationRole).pixmap(200, 200))
    #     # print(self.widget.model() )
    #     # print(ad)
    #     # print('\n-----------\n')
        
